// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8GWXKn5ocojDCFRDWPUbUttpfu9mhbjI',
    appId: '1:597128019581:web:715882be844925bbde3b14',
    messagingSenderId: '597128019581',
    projectId: 'leafy-antonym-392902',
    authDomain: 'leafy-antonym-392902.firebaseapp.com',
    storageBucket: 'leafy-antonym-392902.appspot.com',
    measurementId: 'G-D1603RNJXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMBuaM9-dbGAz_LKGVhGt1SRzIk2d3cQw',
    appId: '1:597128019581:android:241240f93ad4a307de3b14',
    messagingSenderId: '597128019581',
    projectId: 'leafy-antonym-392902',
    storageBucket: 'leafy-antonym-392902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlkaeMsr-ak_5H6rSgkYjgP-52WZf25g4',
    appId: '1:597128019581:ios:a8e659f18ff475b9de3b14',
    messagingSenderId: '597128019581',
    projectId: 'leafy-antonym-392902',
    storageBucket: 'leafy-antonym-392902.appspot.com',
    iosBundleId: 'com.example.liveTrackingMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlkaeMsr-ak_5H6rSgkYjgP-52WZf25g4',
    appId: '1:597128019581:ios:a8e659f18ff475b9de3b14',
    messagingSenderId: '597128019581',
    projectId: 'leafy-antonym-392902',
    storageBucket: 'leafy-antonym-392902.appspot.com',
    iosBundleId: 'com.example.liveTrackingMap',
  );
}
